#include <stdio.h>

const char* help(void) {
  printf(
      ""
      "\n"
      "# qdb\n"
      "\n"
      "qdb > CREATE TABLE \"user\" (\"a\" int pk, \"b\" int);\n"
      "\n"
      "## Description\n"
      "\n"
      "qdb is a sqlite like database without a server.\n"
      "All your data are saved to a single file.\n"
      "\n"
      "It's an educational project which shouldn't be use in production.\n"
      "\n"
      "Only a short subset of sqlite syntax is supported. \n"
      "See below for some examples. \n"
      "See [readme.md](https://github.com/qkzk/qdb#requests-syntax) for a "
      "complete syntax description.\n"
      "\n"
      "\n"
      "## Commands\n"
      "\n"
      "Commands aren't request but affects a whole database.\n"
      "\n"
      "Supported commands :\n"
      "\n"
      ".help                 : display this help message\n"
      ".exit                 : exit qdb \n"
      ".tables               : display all your tables descriptions\n"
      ".clear                : erase all your tables from memory\n"
      ".open database.db     : open a save file and load all the tables \n"
      ".save database.db     : save all your tables into a savefile \n"
      ".read requests.sql    : open a text file and execute all the requests. "
      "Stop at first error.\n"
      "\n"
      "## Example of requests\n"
      "\n"
      "CREATE TABLE \"to_drop\" (\"a\" int pk, \"b\" int, \"c\" varchar ( 32 ) "
      ");\n"
      "CREATE TABLE \"user\" (\"a\" int pk, \"b\" int, \"c\" varchar ( 32 ) "
      ");\n"
      "CREATE TABLE \"aze\" (\"a\" int pk );\n"
      "\n"
      "INSERT INTO \"user\" VALUES (123, 456, 'abc');\n"
      "INSERT INTO \"user\" VALUES (789, 123, 'defgh');\n"
      "INSERT INTO \"user\" VALUES (789, 333, 'xyz');\n"
      "INSERT INTO \"user\" VALUES (102, 123, 'tuv');\n"
      "DROP TABLE \"to_drop\";\n"
      "\n"
      "DELETE FROM \"user\" WHERE ( \"b\" = 123 );\n"
      "DELETE FROM \"user\";\n"
      "\n"
      "SELECT \"b\", \"c\", \"a\"  FROM \"user\" WHERE (( \"c\" = 'abc' ) OR ( "
      "\"b\" = 123 ));\n"
      "SELECT \"b\", \"c\", \"a\"  FROM \"user\" WHERE (\"a\" = 123 );\n"
      "SELECT \"b\", \"c\", \"a\"  FROM \"user\";\n"
      "SELECT \"a\"  FROM \"aze\";\n"
      "SELECT *  FROM \"user\";\n"
      "\n"
      "UPDATE  \"user\" SET \"a\" = 999, \"b\" = 3  WHERE (\"a\" = 123);\n"
      "UPDATE  \"user\" SET \"a\" = 999  WHERE (\"a\" = 789);\n"
      "\n"
      "## Remarks\n"
      "\n"
      "- Identifiers (tablename, colname) must be in double quotes: "
      "\"tablename\"\n"
      "- String literal must be in simple quote: 'John Smith'\n"
      "- Integer will be parsed as long (don't overflow, there's no "
      "protection).\n"
      "- Float will be parsed as double (no overflow protection either).\n");
}
